/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import form.menu_admin;
import internal.Internal_pinjam_barang;
import internal.Internal_kembali_barang;
import javax.swing.table.DefaultTableColumnModel;
import java.sql.Connection;
import connect.koneksiDB;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author ENDOG
 */
public class kembali_barang extends javax.swing.JFrame {
    public void itempilih1(){
        Internal_kembali_barang pd = new Internal_kembali_barang();
        pd.cek = this;
        
        lblIDPin.setText(idPinjam);
        lblpeminjam.setText(peminjam);
        lbltglpin.setText(tglPinjam);
        lblIDBar.setText(idbarang);
        lblnama.setText(namabarang);
        lbljmlpin.setText(jumlahPinjam);
    }
    
    public String idPinjam,peminjam,tglPinjam,idbarang,namabarang,tanggalkembali,jumlahPinjam;
    
    public String idPinjam1(){
        return idPinjam;
    }
    public String peminjam(){
        return peminjam;
    }
    public String tglPinjam(){
        return tglPinjam;
    }
    public String idbarang(){
        return idbarang;
    }
    public String namabarang(){
        return namabarang;
    }
    public String tanggalKembali(){
        return tanggalkembali;
    }
    public String jumlahPinjam(){
        return jumlahPinjam;
    
    }
    
    private void kosong(){
        
        lblIDPin.setText("-");
        lblpeminjam.setText("-");
        lbltglpin.setText("-");
        lblIDBar.setText("-");
        lblnama.setText("-");
        lbljmlpin.setText("-");
        lbltglkembali.setText("-");
    }

    /**
     * Creates new form kembali_barang
     */
    public kembali_barang() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        idPinjam1();
        
        new Thread(){
        public void run(){
            while (true){
            Calendar kal = new GregorianCalendar();
            int tahun = kal.get(Calendar.YEAR);
            int bulan = kal.get(Calendar.MONTH)+1;
            int hari = kal.get(Calendar.DAY_OF_MONTH);
            int jam = kal.get(Calendar.HOUR_OF_DAY);
            int menit = kal.get(Calendar.MINUTE);
            int detik = kal.get(Calendar.SECOND);
            String tanggal = hari+" - "+bulan+" - "+tahun;
            String waktu1 = "["+jam+":"+menit+":"+detik+"]";
            String waktu2 = jam+" - "+menit+" - "+detik;
            lbltglkembali.setText(tanggal);
            }
    }
    }.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbltglpin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnprocess = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblIDPin = new javax.swing.JLabel();
        lblpeminjam = new javax.swing.JLabel();
        lblIDBar = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lbljmlpin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbltglkembali = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(56, 71, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KEMBALI BARANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel7)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(2, 118, 168));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Peminjam");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal Pinjam");

        lbltglpin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbltglpin.setForeground(new java.awt.Color(255, 255, 255));
        lbltglpin.setText("-");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Barang");

        btnsearch.setBackground(new java.awt.Color(204, 204, 255));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\search.png")); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Barang");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Pinjam");

        btnprocess.setBackground(new java.awt.Color(204, 204, 255));
        btnprocess.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnprocess.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\Process.png")); // NOI18N
        btnprocess.setText("PROCESS");
        btnprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocessActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 204, 255));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\cancel.png")); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        lblIDPin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblIDPin.setForeground(new java.awt.Color(255, 255, 255));
        lblIDPin.setText("-");

        lblpeminjam.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblpeminjam.setForeground(new java.awt.Color(255, 255, 255));
        lblpeminjam.setText("-");

        lblIDBar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblIDBar.setForeground(new java.awt.Color(255, 255, 255));
        lblIDBar.setText("-");

        lblnama.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("-");

        lbljmlpin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbljmlpin.setForeground(new java.awt.Color(255, 255, 255));
        lbljmlpin.setText("-");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Kembali");

        lbltglkembali.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbltglkembali.setForeground(new java.awt.Color(255, 255, 255));
        lbltglkembali.setText("-");

        btnback.setBackground(new java.awt.Color(204, 204, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\back.png")); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbltglpin, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(lblpeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIDBar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIDPin, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnama, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lbljmlpin, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lbltglkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnprocess)
                .addGap(84, 84, 84)
                .addComponent(btncancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnback))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnback)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIDPin)
                    .addComponent(btnsearch)
                    .addComponent(jLabel6)
                    .addComponent(lblnama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblpeminjam)
                    .addComponent(jLabel8)
                    .addComponent(lbljmlpin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbltglpin)
                    .addComponent(jLabel9)
                    .addComponent(lbltglkembali))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIDBar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprocess)
                    .addComponent(btncancel))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        Internal_kembali_barang fdb = new Internal_kembali_barang();
        fdb.cek = this;
        fdb.setVisible(true);
        fdb.setResizable(true);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new  SimpleDateFormat("yyyy-MM-dd");
        String tanggal = format.format(cal.getTime());
        try {
            Connection c = koneksiDB.koneksidb();
            if ("".equals(lblIDPin.getText())||
                 "".equals(lblpeminjam.getText())||
                 "".equals(lbltglpin)||
                "".equals(lblIDBar.getText())||
                "".equals(lblnama.getText())||
                "".equals(lbltglpin)||
                "".equals(lbljmlpin.getText())){
                JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
                  }else {
                 String sqlkode = "INSERT INTO kembali_barang"
                        +" values ('"+this.lblIDPin.getText()+"',"
                        +" '"+this.lblpeminjam.getText()+"',"
                        +" '"+this.lbltglpin.getText()+"',"
                        +" '"+this.lblIDBar.getText()+"',"
                        +" '"+this.lblnama.getText()+"',"
                        +" '"+tanggal+"',"
                        +" '"+this.lbljmlpin.getText()+"')";
            
                PreparedStatement p = (PreparedStatement)c.prepareStatement(sqlkode);
                p.executeUpdate();
               
              

               koneksiDB s = new koneksiDB();
                            
                String jmlkeluar2 = s._getValue("SELECT jml_barang FROM barang WHERE id_barang='"+lblIDBar.getText().toString()+"'");
                String jumlah = s._getValue("SELECT jml_keluar FROM stok WHERE id_barang='"+lblIDBar.getText().toString()+"'");
                String jumlah2 = s._getValue("SELECT jml_masuk FROM stok WHERE id_barang='"+lblIDBar.getText().toString()+"'");
                int jmlkluar1 = Integer.parseInt(this.lbljmlpin.getText());
                int jmlkluar2 = Integer.parseInt(jmlkeluar2);
                
                int jml = Integer.parseInt(jumlah);
                int jml2 = Integer.parseInt(jumlah2);
                int total = jmlkluar2 + jmlkluar1;
                int total2 = jmlkluar1 + jml2;
                int total3 = jml + jmlkluar1;
                int jumlh = total2 - total3;
               
               
                 
              s.RunSQL("UPDATE stok SET jml_masuk = '"+total2+"', jml_keluar = '"+total3+"', total_barang = '"+jumlh+"' WHERE id_barang = '"+this.lblIDBar.getText().toString()+"'");
              s.RunSQL("UPDATE barang SET jml_barang = '"+total+"'  WHERE id_barang = '"+lblIDBar.getText().toString()+"'");
              s.RunSQL("DELETE FROM pinjam_barang WHERE id_pinjam = '"+lblIDBar.getText().toString()+"'");
              
               p.close();
                    }
                    
              
            
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "SALAH"+ex.getMessage());
            
        }
    }//GEN-LAST:event_btnprocessActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        menu_user tp = new menu_user();
        tp.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kembali_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kembali_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kembali_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kembali_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kembali_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprocess;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIDBar;
    private javax.swing.JLabel lblIDPin;
    private javax.swing.JLabel lbljmlpin;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblpeminjam;
    private javax.swing.JLabel lbltglkembali;
    private javax.swing.JLabel lbltglpin;
    // End of variables declaration//GEN-END:variables
}
