/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import internal.Internal_pinjam_barang;
import javax.swing.table.DefaultTableColumnModel;
import java.sql.Connection;
import connect.koneksiDB;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.Calendar;

/**
 *
 * @author ENDOG
 */
public class pinjam_barang extends javax.swing.JFrame {
    public void idPinjam(){
        try {
            Connection c = koneksiDB.koneksidb();
            String sql = "SELECT RIGHT(id_pinjam,2)AS id_pinjam FROM pinjam_barang";
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery(sql);
            if (rs.first()==false) {
                txtIDPin.setText("PB001");
            } else {
                rs.last();
                int idd = rs.getInt(1)+1;
                String cno = String.valueOf(idd);
                int pjg_cno = cno.length();
                for (int i = 0 ; i < 2-pjg_cno; i++);
                {
                    int cnoo = Integer.parseInt(cno);
                    if(cnoo > 99){
                        cno=""+cno;
                    }
                    else if(cnoo > 9){
                        cno="0"+cno;
                    }else{
                        cno="00"+cno;
                    }
                    //cno="00"+cno;
                }{
                txtIDPin.setText("PB"+cno);
            }
            }
        } catch (Exception e) {
            System.out.println("Maaf Terjadi Kesalahan Pada ID Pinjam "+e.getMessage());
        }
    }
    
        public void itempilih(){
        Internal_pinjam_barang pd = new Internal_pinjam_barang();
        pd.cek = this;
        txtIDBar.setText(idBarang);
        txtnama.setText(namaBarang);
        lbltersedia.setText("Stok Tersedia: "+jml);
    }
    public String idBarang,namaBarang,jml;
    
    public String getIdBarang(){
        return idBarang;
    }
    public String getNamaBarang(){
        return namaBarang;
    }
    public String getStokBarang(){
        return jml;
    }
    
    private void kosong(){
        txtpeminjam.setText("");
        txtIDBar.setText("");
        txtnama.setText("");
        txtjml.setText("");
    }

    /**
     * Creates new form pinjam_barang
     */
    public pinjam_barang() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        idPinjam();
        
        new Thread(){
        public void run(){
            while (true){
            Calendar kal = new GregorianCalendar();
            int tahun = kal.get(Calendar.YEAR);
            int bulan = kal.get(Calendar.MONTH)+1;
            int hari = kal.get(Calendar.DAY_OF_MONTH);
            int jam = kal.get(Calendar.HOUR_OF_DAY);
            int menit = kal.get(Calendar.MINUTE);
            int detik = kal.get(Calendar.SECOND);
            String tanggal = hari+" - "+bulan+" - "+tahun;
            String waktu1 = "["+jam+":"+menit+":"+detik+"]";
            String waktu2 = jam+" - "+menit+" - "+detik;
            txttglpin.setText(tanggal);
            }
    }
    }.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDPin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpeminjam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttglpin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDBar = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtjml = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbltersedia = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        btnprocess = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(56, 71, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PINJAM BARANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel7)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(2, 118, 168));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Pinjam");

        txtIDPin.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Peminjam");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal Pinjam");

        txttglpin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txttglpin.setForeground(new java.awt.Color(255, 255, 255));
        txttglpin.setText("-");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Barang");

        btnsearch.setBackground(new java.awt.Color(204, 204, 255));
        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\search.png")); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Barang");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Pinjam");

        lbltersedia.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lbltersedia.setForeground(new java.awt.Color(255, 255, 255));
        lbltersedia.setText("jLabel9");

        btnprocess.setBackground(new java.awt.Color(204, 204, 255));
        btnprocess.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnprocess.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\Process.png")); // NOI18N
        btnprocess.setText("PROCESS");
        btnprocess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocessActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 204, 255));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\cancel.png")); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(204, 204, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\back.png")); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txttglpin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIDPin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIDBar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsearch))
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtjml, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltersedia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnprocess)
                        .addGap(86, 86, 86)
                        .addComponent(btncancel)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnback))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnback)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtIDBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lbltersedia)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttglpin)
                    .addComponent(jLabel8)
                    .addComponent(txtjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprocess)
                    .addComponent(btncancel))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        Internal_pinjam_barang fdb = new Internal_pinjam_barang();
        fdb.cek = this;
        fdb.setVisible(true);
        fdb.setResizable(true);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnprocessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocessActionPerformed
        // TODO add your handling code here:
        Calendar kal = Calendar.getInstance();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = format.format(kal.getTime());

        try {
            Connection c = koneksiDB.koneksidb();
            if ("".equals(txtIDPin.getText())||
                "".equals(tanggal)||
                "".equals(txtpeminjam.getText())||
                "".equals(txtIDBar.getText())||
                "".equals(txtnama.getText())||
                "".equals(txtjml.getText()) ) {
                JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR",JOptionPane.WARNING_MESSAGE);
            }else{
                
                koneksiDB kon = new koneksiDB();
                            
                String jmlkeluar2 = kon._getValue("SELECT jml_barang FROM barang WHERE id_barang='"+txtIDBar.getText().toString()+"'");
                String jmlkeluar1 = kon._getValue("SELECT jml_keluar FROM stok WHERE id_barang='"+txtIDBar.getText().toString()+"'");
                String jumlah = kon._getValue("SELECT jml_masuk FROM stok WHERE id_barang='"+txtIDBar.getText().toString()+"'");
                int jmlhkeluar1 = Integer.parseInt(this.txtjml.getText());
                int jmlhkeluar2 = Integer.parseInt(jmlkeluar2);
                int jmlkeluar3 = Integer.parseInt(jmlkeluar1);
                int jml = Integer.parseInt(jumlah);
                int total = jmlhkeluar2 - jmlhkeluar1;
                int total2 = jmlkeluar3 + jmlhkeluar1;
                int jmlh = jml - total2;
                
                    if(jmlhkeluar1 >= jmlhkeluar2){
                JOptionPane.showMessageDialog(this, "Maaf jumlah yang dikeluarkan melebihi stok yang tersedia");
                }else{
                        String sqlkode = "INSERT INTO pinjam_barang"
                        +" VALUES ('"+this.txtIDPin.getText()+"',"
                        +" '"+tanggal+"',"
                        +" '"+this.txtpeminjam.getText()+"',"
                        +" '"+this.txtIDBar.getText()+"',"
                        +" '"+this.txtnama.getText()+"',"
                        +" '"+this.txtjml.getText()+"')";
                        
                        PreparedStatement q = c.prepareStatement(sqlkode);
                        q.executeUpdate();
                        q.close();
                        
                        kon.RunSQL("UPDATE stok SET jml_keluar = '"+total2+"', total_barang = '"+jmlh+"' WHERE id_barang = '"+this.txtIDBar.getText().toString()+"'");
                        kon.RunSQL("UPDATE barang SET jml_barang = '"+total+"'  WHERE id_barang = '"+txtIDBar.getText().toString()+"'");
                    }
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "terjadi Kesalahan pada saat menyimpan"+ex.getMessage());
        }
        idPinjam();
        kosong();
    }//GEN-LAST:event_btnprocessActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        idPinjam();
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        menu_user tp = new menu_user();
        tp.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprocess;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbltersedia;
    private javax.swing.JTextField txtIDBar;
    private javax.swing.JTextField txtIDPin;
    private javax.swing.JTextField txtjml;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpeminjam;
    private javax.swing.JLabel txttglpin;
    // End of variables declaration//GEN-END:variables
}
