/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.table.DefaultTableColumnModel;
import java.sql.Connection;
import connect.koneksiDB;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.io.File;

/**
 *
 * @author ENDOG
 */
public class supplier extends javax.swing.JFrame {
    private String sIDSup,sNamaSup,sAlmtSup,sTelpSup;
    private DefaultTableModel model = new DefaultTableModel(
            new String[][]{{null,null,null}},
            new String[]{"ID Supplier","Nama Supplier","Alamat Supplier","Telepon Supplier"}){
            public boolean isCellEditable(int rowindex, int collindex){
                return false;
            }
        };
    private ResultSet Rs;
    
    public void supplier(){
    try {
        Connection c = koneksiDB.koneksidb();
        String sql="SELECT right(id_supplier,2)as id_supplier from supplier";
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery(sql);
        if (rs.first()==false) {
            txtIDSup.setText("SU001");
        } else {
            rs.last();
            int no=rs.getInt(1)+1;
            String mno=String.valueOf(no);
            int pjg_mno=mno.length();
            for (int i = 0; 1 < 2-pjg_mno; i++); 
            {
                mno="00"+mno;
            }{
            txtIDSup.setText("SU"+mno);
        }
        }
    } catch (Exception e) {
        System.out.println("Maaf Terjadi Kesalahan"+e.getMessage());
    }
}

    private void loaddata(){
    try {
        Statement stmt = koneksiDB.koneksi.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        Rs = (ResultSet)stmt.executeQuery("SELECT `id_supplier`, `nama_supplier`, `alamat_supplier`, `telp_supplier` FROM `supplier`");
        
        while (Rs.next()) {            
            sIDSup = Rs.getString(1);
            sNamaSup = Rs.getString(2);
            sAlmtSup = Rs.getString(3);
            sTelpSup = Rs.getString(4);
            this.model.addRow(new String[]{sIDSup,sNamaSup,sAlmtSup,sTelpSup});
        }
        tblsupplier.setModel(model);
    } catch (SQLException sqle) {
        sqle.printStackTrace();
    }
    tblsupplier.setModel(model);
}

private void cleartable(){
    model = new javax.swing.table.DefaultTableModel(
            new Object[][]{
                {null,null,null}
            },
            new String[]{"ID Supplier","Nama Supplier","Alamat Supplier","Telepon Supplier"}
    );
    model.removeRow(0);
    tblsupplier.setModel(model);
}

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        Dimension screensize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension framesize=getSize();
        setLocation((screensize.width - framesize.width)/2,
                    (screensize.height - framesize.height)/2);
        
        aktif(false);
        settambah(true);
        supplier();
        loaddata();
        model.removeRow(0);
    }
    
    private void kosong () {
        txtIDSup.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtnotlp.setText("");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIDSup = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnotlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsupplier = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        txtalamat = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 118, 168));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Supplier ");

        txtnama.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Supplier");

        txtIDSup.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtIDSup.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No Telepon");

        txtnotlp.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        tblsupplier.setBackground(new java.awt.Color(204, 204, 255));
        tblsupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblsupplier.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tblsupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsupplier);

        btnadd.setBackground(new java.awt.Color(204, 204, 255));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\Add.png")); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(204, 204, 255));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\save.png")); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(204, 204, 255));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\Edit.png")); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(204, 204, 255));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\delete.png")); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 204, 255));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\cancel.png")); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        txtalamat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        btnback.setBackground(new java.awt.Color(204, 204, 255));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\ENDOG\\Documents\\NetBeansProjects\\Inventaris\\src\\image\\back.png")); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(29, 29, 29)
                .addComponent(btnsave)
                .addGap(27, 27, 27)
                .addComponent(btnedit)
                .addGap(26, 26, 26)
                .addComponent(btndelete)
                .addGap(18, 18, 18)
                .addComponent(btncancel)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtIDSup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnotlp)
                            .addComponent(txtalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnback))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnback)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnotlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnsave)
                    .addComponent(btnedit)
                    .addComponent(btndelete)
                    .addComponent(btncancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel2.setBackground(new java.awt.Color(56, 71, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA SUPPLIER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupplierMouseClicked
        // TODO add your handling code here:
        aktif(true);
        setsimpan(false);
        int baris = tblsupplier.getSelectedRow();
        txtIDSup.setText(tblsupplier.getValueAt(baris,0).toString());
        txtnama.setText(tblsupplier.getValueAt(baris,1).toString());
        txtalamat.setText(tblsupplier.getValueAt(baris,2).toString());
        txtnotlp.setText(tblsupplier.getValueAt(baris,3).toString());
    }//GEN-LAST:event_tblsupplierMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        supplier();
        aktif(true);
        setTombol(false);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        int a;
        a = JOptionPane.showConfirmDialog(this, "Apa Anda Yakin Ingin Menyimpan Data Tersebut?","Informasi",JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_OPTION)
        try {
            Connection c = koneksiDB.koneksidb();
            if ("".equals(txtnama.getText())||
                "".equals(txtalamat.getText())||
                "".equals(txtnotlp.getText()) ){
                JOptionPane.showMessageDialog(this, "Harap lengkapi Data","ERROR",JOptionPane.WARNING_MESSAGE);
            } else {
                String sqlkode = "INSERT INTO supplier"
                +" VALUES ('"+this.txtIDSup.getText()+"',"
                +" '"+this.txtnama.getText()+"',"
                +" '"+this.txtalamat.getText()+"',"
                +" '"+this.txtnotlp.getText()+"')";
                PreparedStatement p = (PreparedStatement)c.prepareStatement(sqlkode);
                p.executeUpdate();
                p.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SALAH"+ex.getMessage());
        }
        cleartable();
        txtIDSup.setText("");
        txtnama.setText("");
        txtalamat.setText("");
        txtnotlp.setText("");
        aktif(false);
        settambah(true);
        supplier();
        loaddata();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            Connection c = koneksiDB.koneksidb();
            if ("".equals(txtnama.getText())||
                "".equals(txtalamat.getText())||
                "".equals(txtnotlp.getText())){
                JOptionPane.showMessageDialog(this, "Harap lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
            } else {
                String id = txtIDSup.getText();
                String nama = txtnama.getText();
                String almt = txtalamat.getText();
                String telp = txtnotlp.getText();
                String sqlkode = "UPDATE `supplier` SET `nama_supplier`='"+nama+"',`alamat_supplier`='"+almt+"',`telp_supplier`='"+telp+"' WHERE `id_supplier`='"+id+"'";

                PreparedStatement p = (PreparedStatement)c.prepareStatement(sqlkode);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(rootPane, "Berhasil Menyimpan Perubahan");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }finally{
            cleartable();
            aktif(false);
            settambah(true);

            //txtIDSup.setText("");
            txtnama.setText("");
            txtalamat.setText("");
            txtnotlp.setText("");
            supplier();
            loaddata();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i = tblsupplier.getSelectedRow();
        if (i==-1) {
            return;
        }
        String id = (String)model.getValueAt(i, 0);
        String no = txtIDSup.getText();

        int a;
        a = JOptionPane.showConfirmDialog(this, "Apa anda yakin ingin menghapus data tersebut?","Peringatan",JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.YES_OPTION) {
            try {
                Connection c = koneksiDB.koneksidb();
                String sql = "DELETE FROM `supplier` WHERE `id_supplier` = ?";

                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, no);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            }
            finally{
                cleartable();
                loaddata();
                supplier();
                aktif(true);
                settambah(true);
                //                txtid.setText("");
                txtnama.setText("");
                txtalamat.setText("");
                txtnotlp.setText("");
            }
        }
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        supplier();
        loaddata();
        kosong();
        aktif(false);
        setbatal(true);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        menu_admin tp = new menu_admin();
        tp.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsupplier;
    private javax.swing.JTextField txtIDSup;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotlp;
    // End of variables declaration//GEN-END:variables
private void aktif(boolean x){
    txtIDSup.setEditable(x);
    txtnama.setEditable(x);
    txtalamat.setEditable(x);
    txtnotlp.setEditable(x);
}
private void setTombol(boolean t){
    btnadd.setEnabled(t);
    btnsave.setEnabled(!t);
    btnedit.setEnabled(t);
    btndelete.setEnabled(t);
}
private void setsimpan(boolean k){
    btnadd.setEnabled(k);
    btnsave.setEnabled(k);
    btnedit.setEnabled(!k);
}
private void setbatal(boolean b){
    btnadd.setEnabled(b);
    btnsave.setEnabled(!b);
    btnedit.setEnabled(!b);
    btndelete.setEnabled(b);
}
private void settambah(boolean r){
    btnadd.setEnabled(r);
    btnsave.setEnabled(!r);
    btnedit.setEnabled(!r);
    btndelete.setEnabled(r);
}
}
